### ISSUE TITLE
Yanoushek, Thank you

### ISSUE THREAD

**Issue by yepher** [YANOUSHek/LogCat#10]
Yanoushek,

Sorry this is not really and issues. I just wanted to say thank you for sharing LogCat. Many of us are using it every single day and rely on it very heavily to get their job done faster and easier.

Do you still use it?

-- Yepher

**Comment by YANOUSHek** [comment]
Hi Yepher,

thanks for the kind words. Unfortunately (or fortunately :)) I'm not doing any Android development at the moment so I'm not a regular user of LogCat anymore. I did use it all the time during my Android adventures though.

I hope that I'll manage to get some free time to add a couple new features to LogCat in the near future.
