### ISSUE TITLE
How to connect to my logcat?

### ISSUE THREAD

**Issue by amykaroline** [YANOUSHek/LogCat#11]
Ok, this might be obvious... but I cannot find a way to link the application to my logcat's output.  How do you do this?

Update:  AH, I see I do not need to actually give it the location of my android sdk.  In fact, I just needed to unplug and replug my device.  Thanks for this tool!

**Comment by YANOUSHek** [comment]
Try downloading the current version. I've rolled back changes that embedded adb inside LogCat and now you'll have to browse for your adb location on your system. Then it should work without the need to connect to a device – just plug it in, start LogCat and you're ready to go.
